jobs:
  - name: speedtest
    command: /opt/speedtest2mqtt.sh
    shell: /bin/bash
    schedule: "*/5 * * * *"
    env_file: /tmp/container.env
    captureStderr: false
    captureStdout: true
    concurrencyPolicy: Forbid
